version: "3.7"

services:
  postfix:
    image: boky/postfix
    networks:
      - proxy-net
      - default
    restart: always
    ports:
     - "2525:587"
    env_file: .env
    volumes:
      - ./docker-runtime/certs:/etc/certs
        #      - ./docker-runtime/postconf/master.cf:/etc/postfix/master.cf

networks:
  proxy-net:
    external: true

